#ddev-generated
hooks:
  post-start:
    - exec: nohup bash -c 'if [ -z "${DDEV_BROOKSDIGITAL_BASE_README_WATCH_DISABLED-}" ]; then { ahoy -f /var/www/html/.ddev/brooksdigital/base/.ahoy.brooksdigital-base.readme.yml watch & } ; fi' > /dev/null 2>&1
